name: "Acceptance tests"

on:
  pull_request:
    branches:
      - main

jobs:
  get-changed-files:
    runs-on: ubuntu-latest
    outputs:
      images: ${{ steps.generate-matrix.outputs.images }}
      dockerfiles: ${{ steps.generate-matrix.outputs.dockerfiles }}
      acceptance_tests: ${{ steps.generate-matrix.outputs.acceptance_tests }}
    name: Get changed files
    steps:
      - uses: actions/checkout@v3

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v22.1
      - name: ğŸ— Set up yq
        uses: frenck/action-setup-yq@v1
      - name: Generate matrix args for changed files
        id: generate-matrix
        run: bash -c '.github/workflows/scripts/generate-changed-files-matrix.sh ${{ steps.changed-files.outputs.all_changed_files }}'

  test-changed-images:
    uses: ./.github/workflows/build-image-base.yml
    with:
      image: ${{ fromJson(needs.get-changed-files.outputs.images) }}
      dockerfile: ${{ fromJson(needs.get-changed-files.outputs.dockerfiles) }}
      has_acceptance_tests: ${{ fromJson(needs.get-changed-files.outputs.acceptance_tests) }}
      push: false
